export const CHART_TYPE = {
    VERTICAL_BAR_CHART: 'VERTICAL_BAR_CHART',
    HORIZONTAL_BAR_CHART: 'HORIZONTAL_BAR_CHART',
    PIE_CHART: 'PIE_CHART',
    DONUT_CHART: 'DONUT_CHART',
    LINE_CHART: 'LINE_CHART'
}